name: Java QA Automation CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  api-tests:
    name: API Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}

      - name: Run API Tests
        run: |
          mvn clean test \
            -DsuiteXml=testng-api.xml \
            -Denv=qa

      - name: Upload API Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: api-test-reports
          path: test-output


  web-tests:
    name: Web Tests
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        browser: [chrome, firefox]
        env: [qa]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}

      - name: Install Google Chrome
        if: matrix.browser == 'chrome'
        run: |
          wget -q -O /tmp/chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i /tmp/chrome.deb || sudo apt-get -f install -y
          google-chrome --version

      - name: Verify Firefox
        if: matrix.browser == 'firefox'
        run: firefox --version

      - name: Run Web Tests
        run: |
          mvn clean test \
            -DsuiteXml=testng-web.xml \
            -Dbrowser=${{ matrix.browser }} \
            -Denv=${{ matrix.env }}

      - name: Upload Web Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: web-test-reports-${{ matrix.browser }}-${{ matrix.env }}
          path: test-output
